### ISSUE TITLE
Favicon not present in `/public`

### ISSUE THREAD

**Issue by SRINJAYDASGUPTA-Git** [Ishita0807/travelapp#1]
There is no `favicon.ico` in `/public` folder. a favicon is required for making the website more attractive ad appealing.
@Ishita0807

**Comment by SRINJAYDASGUPTA-Git** [comment]
I have the .ico and i want to contribute 🐸

**Comment by Ishita0807** [comment]
Issue has been assigned to you !

**Comment by SRINJAYDASGUPTA-Git** [comment]
PR Merged
